### ISSUE TITLE
required has no effect

### ISSUE THREAD

**Issue by dgsiegel** [medienbaecker/kirby-link-field#15]
`required: true` does not seem to have an effect on this field. According to the Kirby docs _the field has to be filled in correctly to be saved._ But it behaves like a normal text field with no validation at all. Would be nice if it would behave like the original Url field.

```
fields:
  button:
    label:  Button
    type:   link
    required: true
```
