### ISSUE TITLE
Kirby Builder Plugin

### ISSUE THREAD

**Issue by aristotheme** [medienbaecker/kirby-link-field#2]
Hi 
I cannot use your plugin in Kirby Builder 
[Kirby Builder](https://github.com/TimOetting/kirby-builder)
It says: **type is not defined**
How can I solve this issue? Could you please help me?

Regards

**Comment by medienbaecker** [comment]
I tried to reproduce your issue and downloaded the builder field with a fresh Kirby 3 Starterkit. Seems to work:

![builder](https://user-images.githubusercontent.com/7975568/51443737-e9644400-1ced-11e9-83f1-bb9e0b9df519.gif)

What version of Kirby and the builder field do you use? Could you please share the blueprint? Thank you!

**Comment by aristotheme** [comment]
Yes It works like that but If I try to put it inside accordion ( after text field )

**Comment by medienbaecker** [comment]
You mean in the same fieldset? Still works for me:

![builder-works](https://user-images.githubusercontent.com/7975568/51483235-dce8f580-1d98-11e9-9d26-bbdcaeaee891.gif)

**Comment by aristotheme** [comment]
Yess exactly! :)

Could you please write to me that's blueprint ?

**Comment by medienbaecker** [comment]
This is the blueprint for the page you see in the GIF:

```yml
title: Default
preset: page
fields:
  builder:
    type: builder
    fieldsets:
      aristotest:
        label: Text
        fields:
          text:
            label: Text
            type: textarea
          link:
            label: Link
            type: link
```

**Comment by aristotheme** [comment]
Thank you so much Thomas!
Now it works well :)

I realised It my fault :)

**Comment by aristotheme** [comment]
One More thing Thomas :)

How can I render it in php?
like that `<?= $data->buttonLink() ?>`
I got error :)

**Comment by medienbaecker** [comment]
It's a yaml encoded value. You can see that in the content file:

```yml
----

Button: 

link: mail@medienbaecker.com
type: email

----
```

…or another example:

```yml
----

Button: 

link: about-us
type: page

----
```

That's because I figured you will probably want to do something completely different with an email link compared to a page link or simple URL.

In your template you could do something like this:
```php
<?php
  $buttonType = $page->button()->yaml()["type"];
  $buttonLink = $page->button()->yaml()["link"];
?>

<?php if($buttonType == "email"): ?>

  <a href="mailto:<?= $buttonLink ?>">Write an email</a>

<?php elseif($buttonType == "page"): ?>

  <?php if($buttonPage = page($buttonLink)): ?>
    <a href="<?= $buttonPage->url() ?>"><?= $buttonPage->title() ?></a>
  <?php endif ?>

<?php else: ?>

  <a href="<?= $buttonLink ?>"><?= $buttonLink ?></a>

<?php endif ?>
```
It's of course totally up to you what you do with those two values.
