### ISSUE TITLE
'type is not defined' inside structure field

### ISSUE THREAD

**Issue by S1SYPHOS** [medienbaecker/kirby-link-field#4]
Hey there,
I'm encountering the same problem as #2, but with a (regular) structure field - but what's weird, a while ago it did work and I added some entries, and *those* are still displayed correctly.

The blueprint in question looks like this:
```yml
      slider:
        label: Slider
        type: structure
        fields:
          title:
            label: Title
            type:  text
          link:
            label: Link
            type: link
          text:
            label: Text
            type:  textarea
```
